name: Build static Storybook
on:
  workflow_call:
    inputs:
      artifact-name:
        description: 'Artifact name to be downloaded later. "-storybook" is appended to the end.'
        required: true
        type: string

env:
  FONTAWESOME_PACKAGE_TOKEN: ${{ secrets.FONTAWESOME_PACKAGE_TOKEN }}

jobs:
  build-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: 'npm'

      - run: npm ci

      - name: Build Storybook
        run: npm run build-storybook
        env:
          GOOGLE_API_KEY: '-'
          FIREBASE_API_KEY: '-'
          STRIPE_API_KEY: '-'

      - name: Archive `storybook-static`
        uses: actions/upload-artifact@v6
        with:
          name: ${{ inputs.artifact-name }}-storybook
          path: storybook-static
          retention-days: 5
