name: Build deployable images
on:
  workflow_call:
    inputs:
      environment:
        description: 'GitHub Environment to use for secrets'
        required: true
        type: string
      build-command:
        description: 'The npm action that is run to build the Angular application.'
        default: 'build'
        required: false
        type: string
      artifact-name:
        description: 'Artifact name to be downloaded later'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      FONTAWESOME_PACKAGE_TOKEN: ${{ secrets.FONTAWESOME_PACKAGE_TOKEN }}
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: 'npm'

      - run: npm ci

      - name: Cache Angular build
        uses: actions/cache@v5
        with:
          path: .angular/cache
          key: ${{ runner.os }}-angular-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('src/**') }}
          restore-keys: |
            ${{ runner.os }}-angular-${{ hashFiles('**/package-lock.json') }}-
            ${{ runner.os }}-angular-

      - name: Build
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
          RECAPTCHA_API_KEY: ${{ secrets.RECAPTCHA_API_KEY }}
          STELA_DOMAIN: ${{ secrets.STELA_DOMAIN }}
          MIXPANEL_TOKEN: ${{ secrets.MIXPANEL_TOKEN }}
          FUSIONAUTH_HOST: ${{ secrets.FUSIONAUTH_HOST }}
        run: npm run ${{ inputs.build-command }}

      - name: Archive `dist`
        uses: actions/upload-artifact@v6
        with:
          name: ${{ inputs.artifact-name }}
          path: dist
          retention-days: 5
